#!/usr/bin/env bash
#
# For a list of available hooks, please refer to https://www.libvirt.org/hooks.html
#

set -e

VM_NAME="$1"
HOOK_NAME="$2"
STATE_NAME="$3"
MISC="${@:4}"

BASEDIR="$(dirname $0)"
HOOKPATH="$BASEDIR/qemu.d/$VM_NAME/$HOOK_NAME.sh"

cd /home/edko/Sandbox/Personal/KVM

if [ -f "$HOOKPATH" ] && [ -s "$HOOKPATH" ] && [ -x "$HOOKPATH" ]; then
    eval \"$HOOKPATH\" "$@"
fi